### ISSUE TITLE
I finished the settle follow document but it seem no data.

### ISSUE THREAD

**Issue by weykon** [pingcap/pingcap.github.io#103]
**Describe the bug**

**To Reproduce**
I read many time and follow each part carefully.
but no valid data appear.

**Expected behavior**

**Screenshots**
![image](https://github.com/pingcap/ossinsight-lite/assets/36456814/4fa51cbb-66ed-4723-a14d-634861d34643)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Browser chrome

**Additional context**
what problem would cause this ?

**Comment by weykon** [comment]
![image](https://github.com/pingcap/ossinsight-lite/assets/36456814/9e4fd9f9-f664-4402-bd60-b95353515c61)
I add this secret like this, and this is using the github new feature UI.

did I set correct ?

**Comment by 634750802** [comment]
Hi, @weykon 

I have visited your GitHub home page, I found you are not open your activity data to public.
![image](https://github.com/pingcap/ossinsight-lite/assets/12960671/ddceac2f-89b6-4b5c-a54f-bb60a8ee7a92)

I think the reason is the default `GITHUB_ACCESS_TOKEN` used by pipeline cannot collect your private activity data.  Checkout [this document](https://github.com/pingcap/ossinsight-lite/blob/main/docs/setup/private-repositories.md) and use an authorized GITHUB_ACCESS_TOKEN to allow pipeline to collect your private activity data.

---

And I suggest you to enable the [Repo sync](https://github.com/weykon/ossinsight-lite/actions/workflows/repo-sync.yml) workflow to auto sync upstream changes (this workflow uses ***force push*** on main branch).

**Comment by 634750802** [comment]
> ![image](https://user-images.githubusercontent.com/36456814/247467270-9e4fd9f9-f664-4402-bd60-b95353515c61.png) I add this secret like this, and this is using the github new feature UI.
> 
> did I set correct ?

Your [Data pipeline workflow](https://github.com/weykon/ossinsight-lite/actions/workflows/pipelines.yml) passed, that means you have configured the `DATABASE_URL` correctly

**Comment by weykon** [comment]
Oh, Thank you for your reply, but I still have a small problem that it does not collect data correctly at most used languages and the other.
![image](https://github.com/pingcap/ossinsight-lite/assets/36456814/4433ca4a-8226-42bf-b36a-7cc8f464a36f)

### Some wrong at running Personal Pipeline.
![image](https://github.com/pingcap/ossinsight-lite/assets/36456814/ad014c74-6f9c-43f8-a2bd-3c59f7664707)

the secret I set: read:discussion, read:repo_hook, read:user, repo, user:follow

**Comment by hooopo** [comment]
> Oh, Thank you for your reply, but I still have a small problem that it does not collect data correctly at most used languages and the other. ![image](https://user-images.githubusercontent.com/36456814/247527286-4433ca4a-8226-42bf-b36a-7cc8f464a36f.png)
> 
> ### Some wrong at running Personal Pipeline.
> ![image](https://user-images.githubusercontent.com/36456814/247528466-ad014c74-6f9c-43f8-a2bd-3c59f7664707.png)
> 
> the secret I set: read:discussion, read:repo_hook, read:user, repo, user:follow

This is the first time I've encountered this error（invalid cursor） as well. I think it might be caused by you not setting the correct token initially, and then setting the correct token later, leading to the previous cursor becoming invalid. I suggest you change to a different dbname or drop the db set in the action, so the pipeline will create a new, clean db.

**Comment by 634750802** [comment]
@weykon 

The most used language SQL is here
https://github.com/pingcap/ossinsight-lite/blob/main/collections/contribution-most-used-languages/template.sql

```
WITH languages AS (
    SELECT language, COUNT(*) as count
    FROM pull_requests pr
    JOIN repos r on pr.repo_id = r.id
    WHERE pr.user_id = (SELECT id FROM curr_user LIMIT 1) AND r.language IS NOT NULL
    GROUP BY language
    ORDER BY count DESC
), total AS (
    SELECT SUM(count) as total FROM languages
)
SELECT language, count, ROUND(count * 100.0 / total, 2) as precentage
FROM languages, total
ORDER BY count DESC
```

This uses the repo's main language. The chart title is misleading. @Mini256

**Comment by weykon** [comment]
Oh really thanks guys !  :)
I'll try again later tonight, I'm enjoying the holidays.

**Comment by weykon** [comment]
> Oh really thanks guys ! :) I'll try again later tonight, I'm enjoying the holidays.

I reset the TiDB, and its view seems to be working fine.
